# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149e1_APkM3zhq1lM9FWYyl6vwF_O9cVk
"""

!pip install matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#sample data
dates=pd.date_range(start='2023-01-01', periods=12, freq='M')
sales=[12, 18, 20, 25, 22, 30, 35, 40, 38, 32, 28, 36]

dates, sales

#line plot
plt.plot(dates, sales)
plt.show()

#scatter plot
plt.scatter(dates, sales)
plt.show()

#bar plot
plt.bar(dates, sales)
plt.show()

#sample data
categories=['A','B','C','D']
values=[25,40,35,50]
categories, values

#bar plot
plt.bar(categories, values)
plt.show()

#sample data
np.random.seed(42)
data=np.random.normal(loc=50, scale=10, size=500)
data

#histogram
plt.hist(data)
plt.show()

#sample data
data=pd.DataFrame({
    'category':['A','B','C','D']*20,
    'value':np.random.randint(10,50,80)
})
data

#box plot
plt.boxplot([data[data['category'] == cat ]['value'] for cat in data['category'].unique()], labels=data['category'].unique())
plt.show()

#sample data
y= np.array([35,25,25,15])
my_labels=["Apples","Banana","Cherries","Dates"]
y, my_labels

#pie chart
plt.pie(y, labels=my_labels)
plt.show()