# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0vn2liroeJpYdg06UltQ5xDLP2DJ5Zs
"""

!pip install matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#sample data
dates= pd.date_range(start='2023-01-01', periods=12, freq='M')
sales_productA=[15, 25, 32, 40, 22, 17, 30, 18, 36, 44, 38, 50]
sales_productB=[12, 18, 25, 28, 30, 40, 33, 38, 44, 50, 42, 55]
dates, sales_productA, sales_productB

#custom line plot
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA)
plt.show()

#custom line plot with labels
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA)
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.show()

#custom line plot for two products
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA, label='Product A')
plt.plot(dates, sales_productB, label='Product B')
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.grid(True)
plt.show()

#custom line plot for two products with manualy style
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA, label='Product A', marker='o', color='y', linestyle='-', linewidth=2)
plt.plot(dates, sales_productB, label='Product B', marker='s', color='b', linestyle='--', linewidth=2)
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.show()

#custom line plot for two products with ggplot style
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA, label='Product A', marker='o', linestyle='-', linewidth=2)
plt.plot(dates, sales_productB, label='Product B', marker='s', linestyle='--', linewidth=2)
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.style.use('ggplot')
plt.show()

#custom line plot for two products with dark_background style
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA, label='Product A', marker='o', linestyle='-', linewidth=2)
plt.plot(dates, sales_productB, label='Product B', marker='s', linestyle='--', linewidth=2)
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.style.use('dark_background')
plt.show()

#To know all available styles (Themes)
print(plt.style.available)
#To use default style
plt.style.use('default')

#Annotate highest sales month
plt.figure(figsize=(12, 6))
plt.plot(dates, sales_productA, label='Product A', marker='o', color='y', linestyle='-', linewidth=2)
plt.title('Monthly sales comparison', fontsize=16)
plt.xlabel('Month', fontsize=14)
plt.ylabel('sales', fontsize=14)
plt.grid(True)
plt.annotate('Highest Sales', xy=(dates[11], sales_productA[11]), xytext=(dates[8], sales_productA[10]+ 8), arrowprops=dict(facecolor='black', arrowstyle='->'))
plt.show()

#sample data
x= np.linspace(0, 10, 100)

#create subplots
fig, axs=plt.subplots(2, 2, figsize=(12, 10))

axs[0,0].plot(x, np.sin(x), 'r')
axs[0,0].set_title('sine wave')

axs[0,1].plot(x, np.cos(x), 'b')
axs[0,1].set_title('cosine wave')

axs[1,0].plot(x, np.tan(x), 'g')
axs[1,0].set_title('Tangent wave')

axs[1,1].plot(x, -np.sin(x), 'm')
axs[1,1].set_title('Negative sine wave')

for ax in axs.flat:
  ax.set(xlabel='X Axis', ylabel='Y Axis')
  ax.grid(True)

plt.tight_layout()
plt.show()